import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf_report(dataset_name, health_data, insights_data):
    """
    Generates a formatted PDF report stream using ReportLab.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    story = []

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#1E1E2E'),
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=15
    )

    h2_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#4338CA'),
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155')
    )

    # Title & Header
    story.append(Paragraph("🤖 AI Data Analyst - Executive Report", title_style))
    story.append(Paragraph(f"Dataset: <b>{dataset_name}</b> | Generated by AI Data Analyst Engine", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#6366F1'), spaceAfter=15))

    # Section 1: Health Score
    story.append(Paragraph("1. Data Health & Quality Profile", h2_style))
    health_text = (
        f"Overall Data Health Score: <b>{health_data.get('score', 0)}%</b> ({health_data.get('grade', 'N/A')})<br/>"
        f"Completeness: {health_data.get('completeness', 0)}% | "
        f"Uniqueness: {health_data.get('uniqueness', 0)}% | "
        f"Consistency: {health_data.get('consistency', 0)}%"
    )
    story.append(Paragraph(health_text, body_style))
    story.append(Spacer(1, 10))

    # Section 2: Key Metrics Table
    story.append(Paragraph("2. Key Performance Indicators (KPIs)", h2_style))
    metrics = insights_data.get("key_metrics", [])
    if metrics:
        table_data = [["Metric Name", "Value", "Notes / Average"]]
        for m in metrics:
            table_data.append([m.get("label", ""), m.get("value", ""), m.get("sub", "")])

        t = Table(table_data, colWidths=[200, 150, 180])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4338CA')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 10),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#F8FAFC')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
            ('TEXTCOLOR', (0,1), (-1,-1), colors.HexColor('#1E293B')),
            ('FONTSIZE', (0,1), (-1,-1), 9),
        ]))
        story.append(t)
    story.append(Spacer(1, 12))

    # Section 3: Summary & Insights
    story.append(Paragraph("3. Executive Insights & Observations", h2_style))
    story.append(Paragraph(f"<b>Summary:</b> {insights_data.get('summary', '')}", body_style))
    story.append(Spacer(1, 6))

    insights_list = insights_data.get("insights", [])
    for idx, insight in enumerate(insights_list, 1):
        story.append(Paragraph(f"• <b>Insight {idx}:</b> {insight}", body_style))
        story.append(Spacer(1, 4))

    story.append(Spacer(1, 10))

    # Section 4: Recommendations
    story.append(Paragraph("4. Strategic Recommendations", h2_style))
    recs = insights_data.get("recommendations", [])
    for idx, rec in enumerate(recs, 1):
        story.append(Paragraph(f"• <b>Action {idx}:</b> {rec}", body_style))
        story.append(Spacer(1, 4))

    doc.build(story)
    buffer.seek(0)
    return buffer
